leftnav:
- identifier: 0aafd4cb-7d5e-6107-dfa1-c161e16af3d0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 712c175d-5785-164b-30b2-acd2f73a355a
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 65ec541b-88c8-b9eb-ee18-80ef874e0b44
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 00c88a64-4348-e79e-4e97-96ce5f933e3e
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 8206e495-d3a8-1289-7844-ff27c7536468
  name: Recitations
  pageRef: /pages/recitations
  weight: 50
- identifier: 597cf42f-580e-77a2-1646-e4ea370fc1f5
  name: Assignments
  pageRef: /pages/assignments
  weight: 60
